package com.personal.offlinewords;

import android.app.*;import android.os.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.media.MediaPlayer;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
    private WordDb db; private LinearLayout root,content,actions; private Word current; private MediaPlayer player; private byte[] pendingExport; private boolean revealed; private View revealHint; private final java.util.ArrayList<Long> history=new java.util.ArrayList<>();
    private final int teal=Color.rgb(15,118,110), ink=Color.rgb(26,38,36), muted=Color.rgb(91,107,103);
    int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new WordDb(this);showLoading();new Thread(()->{try{db.seedIfNeeded(this);runOnUiThread(this::showHome);}catch(Exception e){runOnUiThread(()->error(e));}}).start();}
    TextView text(String s,int sp,int color){TextView v=new TextView(this);v.setText(s==null?"":s);v.setTextSize(sp);v.setTextColor(color);v.setPadding(0,dp(8),0,dp(8));return v;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(18);b.setTextColor(Color.WHITE);b.setBackgroundColor(teal);b.setAllCaps(false);b.setMinHeight(dp(64));b.setPadding(dp(12),dp(10),dp(12),dp(10));return b;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,247,246));TextView bar=text(title,22,Color.WHITE);bar.setTypeface(null,Typeface.BOLD);bar.setBackgroundColor(teal);bar.setPadding(dp(24),dp(22),dp(24),dp(18));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(72)));ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setGravity(Gravity.CENTER_HORIZONTAL);content.setPadding(dp(22),dp(24),dp(22),dp(20));sc.addView(content,new ScrollView.LayoutParams(-1,-1));root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);actions.setPadding(dp(14),dp(8),dp(14),dp(12));actions.setBackgroundColor(Color.rgb(235,240,238));actions.setVisibility(View.GONE);root.addView(actions,new LinearLayout.LayoutParams(-1,-2));setContentView(root);}
    void gap(int h){Space s=new Space(this);content.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
    void showLoading(){base("雅思单词库");content.addView(text("正在初始化离线词库…",18,muted));}
    void showHome(){revealed=true;current=null;base("雅思单词库");int total=db.count("1=1"),mastered=db.count("box=-1"),remaining=total-mastered;TextView hi=text("天水虽宽，不润无根之草",28,ink);hi.setTypeface(null,Typeface.BOLD);content.addView(hi);content.addView(text("当前词库："+db.name("books",db.bookId)+" · "+total+" 词",17,muted));gap(18);Button books=button("管理 / 切换 Excel 词库");books.setContentDescription("导入、切换或删除 Excel 词库");books.setBackgroundColor(Color.rgb(55,92,139));books.setOnClickListener(v->showBookManager());content.addView(books,new LinearLayout.LayoutParams(-1,dp(68)));gap(20);content.addView(text("已标记  "+mastered+"     剩余  "+remaining+"     全局收藏  "+db.favoriteCount(),19,ink));ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(total);p.setProgress(mastered);content.addView(p,new LinearLayout.LayoutParams(-1,dp(18)));content.addView(text(String.format("完成度 %.1f%%",total==0?0:mastered*100.0/total),15,muted));gap(22);Button start=button("开始背单词");start.setContentDescription("开始背单词，进入学习页面");start.setOnClickListener(v->showCard());content.addView(start,new LinearLayout.LayoutParams(-1,dp(72)));gap(12);Button favorites=button("★  导出全局收藏 Excel");favorites.setContentDescription("将所有词库收藏的单词导出到同一个 Excel 文件");favorites.setBackgroundColor(Color.rgb(190,130,32));favorites.setOnClickListener(v->exportExcel(true));content.addView(favorites,new LinearLayout.LayoutParams(-1,dp(68)));gap(12);Button export=button("导出当前词库学习状态");export.setContentDescription("将当前词库的掌握状态导出为 Excel 文件");export.setBackgroundColor(Color.rgb(70,92,87));export.setOnClickListener(v->exportExcel(false));content.addView(export,new LinearLayout.LayoutParams(-1,dp(68)));gap(18);content.addView(text("收藏单词跨所有词库汇总；掌握进度仍按词库独立保存。",16,muted));}
    void showBookManager(){Cursor c=db.books();java.util.ArrayList<Long> ids=new java.util.ArrayList<>();java.util.ArrayList<String> names=new java.util.ArrayList<>();while(c.moveToNext()){long id=c.getLong(0);ids.add(id);names.add((id==db.bookId?"✓  ":"")+c.getString(1)+(id==1?"（默认，不可删除）":""));}c.close();AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Excel 词库管理").setItems(names.toArray(new String[0]),(d,which)->{db.select(ids.get(which),db.profileId);showHome();}).setPositiveButton("导入 Excel",(d,w)->chooseExcel()).setNeutralButton("删除当前词库",null).setNegativeButton("关闭",null).create();dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{if(db.bookId==1){Toast.makeText(this,"默认词库不可删除",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("删除词库？").setMessage("将删除“"+db.name("books",db.bookId)+"”及其全部学习状态，此操作不可恢复。").setPositiveButton("确认删除",(q,w)->{db.deleteBook(db.bookId);dialog.dismiss();showHome();}).setNegativeButton("取消",null).show();}));dialog.show();}
    void chooseExcel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,43);}
    String displayName(android.net.Uri uri){Cursor c=getContentResolver().query(uri,null,null,null,null);try{if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}finally{if(c!=null)c.close();}return "自定义词库";}
    void importExcel(android.net.Uri uri){Toast.makeText(this,"正在导入 Excel…",Toast.LENGTH_SHORT).show();new Thread(()->{try(InputStream in=getContentResolver().openInputStream(uri)){java.util.List<String[]> rows=XlsxImporter.read(in);String n=displayName(uri).replaceFirst("(?i)\\.xlsx$","");long id=db.importBook(n,rows);db.select(id,db.profileId);runOnUiThread(()->{showHome();Toast.makeText(this,"已导入 "+rows.size()+" 个单词",Toast.LENGTH_LONG).show();});}catch(Exception e){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("导入失败").setMessage(e.getMessage()).setPositiveButton("确定",null).show());}}).start();}
    void showCard(){if(current!=null)history.add(current.id);current=db.next();if(current==null){showHome();Toast.makeText(this,"词库已经全部掌握",Toast.LENGTH_LONG).show();return;}renderCard();}
    void renderCard(){revealed=false;base("学习中");content.setGravity(Gravity.CENTER);TextView term=text(current.term,48,ink);term.setGravity(Gravity.CENTER);term.setTypeface(null,Typeface.BOLD);content.addView(term,new LinearLayout.LayoutParams(-1,-2));gap(22);revealHint=text("轻触屏幕任意位置\n查看释义和固定操作按钮",19,muted);((TextView)revealHint).setGravity(Gravity.CENTER);content.addView(revealHint,new LinearLayout.LayoutParams(-1,-2));root.setContentDescription("点击任意位置显示单词详细信息");content.postDelayed(this::playAudio,180);}
    void previousWord(){if(history.isEmpty()){Toast.makeText(this,"已经是第一个单词",Toast.LENGTH_SHORT).show();return;}Word previous=db.wordById(history.remove(history.size()-1));if(previous!=null){current=previous;renderCard();}}
    Button footerButton(String label,int color){Button b=button(label);b.setBackgroundColor(color);return b;}
    void reveal(View hint){if(revealed)return;revealed=true;root.setContentDescription(null);hint.setVisibility(View.GONE);content.setGravity(Gravity.CENTER_HORIZONTAL);TextView ipa=text((current.ipa==null?"":current.ipa)+"  "+(current.pos==null?"":current.pos),20,muted);ipa.setGravity(Gravity.CENTER);content.addView(ipa);gap(8);TextView zh=text(current.zh,28,ink);zh.setTypeface(null,Typeface.BOLD);zh.setGravity(Gravity.CENTER);content.addView(zh,new LinearLayout.LayoutParams(-1,-2));content.addView(text(current.en,17,muted));gap(14);String example=(current.exampleEn==null||current.exampleEn.trim().isEmpty())?"暂无用法说明":current.exampleEn;content.addView(text(example,19,ink),new LinearLayout.LayoutParams(-1,-2));actions.setVisibility(View.VISIBLE);LinearLayout tools=new LinearLayout(this);Button previous=footerButton("← 上一词",Color.rgb(70,92,87));previous.setOnClickListener(v->previousWord());Button sound=footerButton("🔊 再听",teal);sound.setOnClickListener(v->playAudio());tools.addView(previous,new LinearLayout.LayoutParams(0,dp(58),1));tools.addView(sound,new LinearLayout.LayoutParams(0,dp(58),1));actions.addView(tools);Button favorite=footerButton(db.isFavorite(current.id)?"★ 已收藏（点击取消）":"☆ 收藏这个单词",Color.rgb(190,130,32));favorite.setOnClickListener(v->{boolean yes=db.toggleFavorite(current.id);favorite.setText(yes?"★ 已收藏（点击取消）":"☆ 收藏这个单词");Toast.makeText(this,yes?"已加入全局收藏":"已取消收藏",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(58));fp.setMargins(0,dp(8),0,dp(8));actions.addView(favorite,fp);LinearLayout decisions=new LinearLayout(this);Button mark=footerButton("✓ 已掌握",teal);mark.setOnClickListener(v->{db.markMastered(current.id);showCard();});Button next=footerButton("下一个 →",Color.rgb(86,103,99));next.setOnClickListener(v->{db.skip(current.id);showCard();});decisions.addView(mark,new LinearLayout.LayoutParams(0,dp(62),1));decisions.addView(next,new LinearLayout.LayoutParams(0,dp(62),1));actions.addView(decisions);}
    void playAudio(){try{if(player!=null)player.release();String path=current.audio.replace("audio/uk/","audio/");android.content.res.AssetFileDescriptor afd=getAssets().openFd(path);player=new MediaPlayer();player.setDataSource(afd.getFileDescriptor(),afd.getStartOffset(),afd.getLength());afd.close();player.prepare();player.start();}catch(Exception e){fetchAudio();}}
    void fetchAudio(){File cached=new File(getCacheDir(),"audio_"+current.id+".mp3");if(cached.exists()){playFile(cached);return;}String term=current.term;new Thread(()->{try{URL api=new URL("https://api.dictionaryapi.dev/api/v2/entries/en/"+URLEncoder.encode(term,"UTF-8"));HttpURLConnection c=(HttpURLConnection)api.openConnection();c.setConnectTimeout(7000);c.setReadTimeout(7000);JSONArray a=new JSONArray(readAll(c.getInputStream()));JSONArray ps=a.getJSONObject(0).getJSONArray("phonetics");String audio="";for(int i=0;i<ps.length();i++){audio=ps.getJSONObject(i).optString("audio","");if(!audio.isEmpty())break;}if(audio.startsWith("//"))audio="https:"+audio;if(audio.isEmpty())throw new IOException("no audio");try(InputStream in=new URL(audio).openStream();OutputStream out=new FileOutputStream(cached)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);}runOnUiThread(()->playFile(cached));}catch(Exception ex){runOnUiThread(()->Toast.makeText(this,"未找到在线发音",Toast.LENGTH_SHORT).show());}}).start();}
    String readAll(InputStream in)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))>0)o.write(b,0,n);return o.toString("UTF-8");}
    void playFile(File f){try{if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.prepare();player.start();}catch(Exception ignored){}}
    String xe(String s){return s==null?"":s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    void exportExcel(boolean favorites){if(favorites&&db.favoriteCount()==0){Toast.makeText(this,"还没有收藏单词",Toast.LENGTH_SHORT).show();return;}String sheet=favorites?"全局收藏":"学习状态";StringBuilder x=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\"><Worksheet ss:Name=\"").append(sheet).append("\"><Table><Row>");String[] h={"序号","单词","音标","词性","中文释义","状态","最后学习时间"};for(String s:h)x.append("<Cell><Data ss:Type=\"String\">").append(s).append("</Data></Cell>");x.append("</Row>");Cursor c=favorites?db.exportFavorites():db.exportRows();while(c.moveToNext()){x.append("<Row>");for(int i=0;i<7;i++)x.append("<Cell><Data ss:Type=\"String\">").append(xe(c.getString(i))).append("</Data></Cell>");x.append("</Row>");}c.close();x.append("</Table></Worksheet></Workbook>");pendingExport=x.toString().getBytes(StandardCharsets.UTF_8);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/vnd.ms-excel");i.putExtra(Intent.EXTRA_TITLE,favorites?"收藏单词-全局.xls":"学习状态-"+db.name("books",db.bookId)+".xls");startActivityForResult(i,42);}
    @Override protected void onActivityResult(int r,int code,Intent data){super.onActivityResult(r,code,data);if(code!=RESULT_OK||data==null)return;if(r==43){importExcel(data.getData());return;}if(r==42&&pendingExport!=null){try(OutputStream o=getContentResolver().openOutputStream(data.getData())){o.write(pendingExport);Toast.makeText(this,"导出完成",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"导出失败",Toast.LENGTH_SHORT).show();}}}
    void error(Exception e){base("初始化失败");content.addView(text(e.getMessage(),16,Color.RED));}
    @Override public boolean dispatchTouchEvent(android.view.MotionEvent event){if(!revealed&&revealHint!=null){if(event.getAction()==android.view.MotionEvent.ACTION_UP)reveal(revealHint);return true;}return super.dispatchTouchEvent(event);}
    @Override public void onBackPressed(){showHome();}
    @Override protected void onDestroy(){if(player!=null)player.release();db.close();super.onDestroy();}
}
