package com.personal.offlinewords;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaPlayer;
import android.net.Uri;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private WordDb db; private LinearLayout root,content,actions; private Word current; private MediaPlayer player;
    private byte[] pendingExport; private boolean revealed; private View revealHint; private LinearLayout progressHeader; private ProgressBar topProgress; private TextView topProgressText; private FrameLayout checkInPoster; private Uri savedCheckInUri;
    private final ArrayList<Long> history=new ArrayList<>();
    private final int teal=Color.rgb(20,120,105), tealDark=Color.rgb(12,82,75), ink=Color.rgb(29,42,39), muted=Color.rgb(91,107,103), cream=Color.rgb(247,249,247), amber=Color.rgb(212,143,35), red=Color.rgb(184,72,62);

    int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new WordDb(this);showLoading();new Thread(()->{try{db.seedIfNeeded(this);runOnUiThread(this::showHome);}catch(Exception e){runOnUiThread(()->error(e));}}).start();}

    GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    TextView text(String s,int sp,int color){TextView v=new TextView(this);v.setText(s==null?"":s);v.setTextSize(sp);v.setTextColor(color);v.setLineSpacing(dp(2),1.08f);v.setPadding(0,dp(6),0,dp(6));return v;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(17);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setMinHeight(dp(56));b.setPadding(dp(12),dp(8),dp(12),dp(8));b.setBackground(bg(teal,16));return b;}
    void color(Button b,int color){b.setBackground(bg(color,16));}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(cream);TextView bar=text(title,21,Color.WHITE);bar.setTypeface(null,Typeface.BOLD);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(tealDark);bar.setPadding(dp(22),dp(15),dp(22),dp(12));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));progressHeader=new LinearLayout(this);progressHeader.setOrientation(LinearLayout.VERTICAL);progressHeader.setPadding(dp(20),dp(5),dp(20),dp(5));progressHeader.setBackgroundColor(Color.rgb(236,242,239));topProgressText=text("",12,muted);topProgressText.setPadding(0,0,0,dp(2));progressHeader.addView(topProgressText);topProgress=progress(1,0,teal);progressHeader.addView(topProgress,new LinearLayout.LayoutParams(-1,dp(4)));progressHeader.setVisibility(View.GONE);root.addView(progressHeader,new LinearLayout.LayoutParams(-1,dp(32)));ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setGravity(Gravity.CENTER_HORIZONTAL);content.setPadding(dp(20),dp(20),dp(20),dp(24));sc.addView(content,new ScrollView.LayoutParams(-1,-1));root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);actions.setPadding(dp(12),dp(8),dp(12),dp(12));actions.setBackgroundColor(Color.rgb(236,242,239));actions.setVisibility(View.GONE);root.addView(actions,new LinearLayout.LayoutParams(-1,-2));setContentView(root);}
    void gap(int h){Space s=new Space(this);content.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(15),dp(18),dp(15));c.setBackground(bg(Color.WHITE,20));return c;}
    void addCard(View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));content.addView(v,p);}
    ProgressBar progress(int max,int value,int color){ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(Math.max(1,max));p.setProgress(Math.min(value,Math.max(1,max)));if(Build.VERSION.SDK_INT>=21)p.setProgressTintList(android.content.res.ColorStateList.valueOf(color));return p;}
    void progressBlock(LinearLayout box,String title,int value,int max,int color){TextView t=text(title,16,ink);t.setTypeface(null,Typeface.BOLD);box.addView(t);box.addView(progress(max,value,color),new LinearLayout.LayoutParams(-1,dp(10)));box.addView(text(value+" / "+max+(max>0?String.format(Locale.getDefault(),"  ·  %.1f%%",value*100.0/max):""),14,muted));}

    void showLoading(){base("雅思单词库");content.addView(text("正在准备你的离线词库…",18,muted));}
    void showHome(){revealed=true;current=null;base("雅思单词库");int total=db.total(),mastered=db.mastered(),today=db.studiedToday();TextView hi=text("天水虽宽，不润无根之草",27,ink);hi.setTypeface(null,Typeface.BOLD);content.addView(hi);content.addView(text(db.name("books",db.bookId)+"  ·  "+total+" 词",16,muted));gap(10);
        db.ensureRound();int round=db.currentRound(),roundDone=db.roundDone(),roundTotal=db.roundTotal();LinearLayout stats=card();progressBlock(stats,"总掌握进度",mastered,total,teal);stats.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(10)));progressBlock(stats,"第 "+round+" 轮学习进度",roundDone,roundTotal,amber);stats.addView(text("今日已学习 "+today+" 词  ·  今日新掌握 "+db.masteredToday()+" 词  ·  收藏 "+db.favoriteCount()+" 词",15,muted));addCard(stats);
        Button start=button(today==0?"开始今天的学习":"继续学习  →");start.setOnClickListener(v->showCard());addCard(start);
        LinearLayout row=new LinearLayout(this);Button books=button("词库管理");color(books,Color.rgb(62,92,132));books.setOnClickListener(v->showBookManager());Button check=button(db.checkedToday()?"✓ 今日已打卡":"今日打卡");color(check,db.checkedToday()?tealDark:amber);check.setOnClickListener(v->showCheckIn());row.addView(books,new LinearLayout.LayoutParams(0,dp(58),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(58),1);cp.setMargins(dp(8),0,0,0);row.addView(check,cp);addCard(row);
        Button favorites=button("★ 导出全局收藏 Excel");color(favorites,Color.rgb(174,117,30));favorites.setOnClickListener(v->exportExcel(true));addCard(favorites);Button export=button("导出当前词库（含编辑与状态）");color(export,Color.rgb(70,92,87));export.setOnClickListener(v->exportExcel(false));addCard(export);
        content.addView(text("每个 Excel 词库独立保存学习进度；收藏在全部词库间汇总。",14,muted));}

    void showBookManager(){Cursor c=db.books();ArrayList<Long> ids=new ArrayList<>();ArrayList<String> names=new ArrayList<>();while(c.moveToNext()){long id=c.getLong(0);ids.add(id);names.add((id==db.bookId?"✓  ":"")+c.getString(1)+(id==1?"（默认，不可删除）":""));}c.close();AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Excel 词库管理").setItems(names.toArray(new String[0]),(d,w)->{db.select(ids.get(w),db.profileId);showHome();}).setPositiveButton("导入 Excel",(d,w)->chooseExcel()).setNeutralButton("删除当前词库",null).setNegativeButton("关闭",null).create();dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{if(db.bookId==1){Toast.makeText(this,"默认词库不可删除",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("删除词库？").setMessage("将删除“"+db.name("books",db.bookId)+"”及其全部学习状态，此操作不可恢复。").setPositiveButton("确认删除",(q,w)->{db.deleteBook(db.bookId);dialog.dismiss();showHome();}).setNegativeButton("取消",null).show();}));dialog.show();}
    void chooseExcel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,43);}
    String displayName(Uri uri){Cursor c=getContentResolver().query(uri,null,null,null,null);try{if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}finally{if(c!=null)c.close();}return "自定义词库";}
    void importExcel(Uri uri){Toast.makeText(this,"正在导入 Excel…",Toast.LENGTH_SHORT).show();new Thread(()->{try(InputStream in=getContentResolver().openInputStream(uri)){List<String[]> rows=XlsxImporter.read(in);long id=db.importBook(displayName(uri).replaceFirst("(?i)\\.xlsx$",""),rows);db.select(id,db.profileId);runOnUiThread(()->{showHome();Toast.makeText(this,"已导入 "+rows.size()+" 个单词",Toast.LENGTH_LONG).show();});}catch(Exception e){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("导入失败").setMessage(e.getMessage()).setPositiveButton("确定",null).show());}}).start();}

    void showCard(){if(current!=null)history.add(current.id);current=db.next();if(current==null){showHome();Toast.makeText(this,"词库已经全部掌握",Toast.LENGTH_LONG).show();return;}renderCard();}
    void renderCard(){revealed=false;db.ensureRound();int round=db.currentRound(),roundPos=db.roundPosition(),roundTotal=db.roundTotal(),bookPos=db.bookPosition(current.id),bookTotal=db.total();base("学习中");progressHeader.setVisibility(View.VISIBLE);topProgress.setMax(Math.max(1,bookTotal));topProgress.setProgress(bookPos);topProgressText.setText("第 "+round+" 轮  ·  词书位置 "+bookPos+" / "+bookTotal+String.format(Locale.getDefault(),"  ·  %.1f%%",bookTotal==0?0:bookPos*100.0/bookTotal));content.setGravity(Gravity.CENTER);gap(24);LinearLayout wordFocus=card();wordFocus.setGravity(Gravity.CENTER);wordFocus.setBackground(bg(Color.rgb(235,246,241),22));TextView term=text(current.term,47,ink);term.setGravity(Gravity.CENTER);term.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));wordFocus.addView(term,new LinearLayout.LayoutParams(-1,-2));addCard(wordFocus);gap(14);revealHint=text("轻触查看释义",17,muted);((TextView)revealHint).setGravity(Gravity.CENTER);content.addView(revealHint,new LinearLayout.LayoutParams(-1,-2));root.setContentDescription("点击任意位置显示单词详细信息");content.postDelayed(this::playAudio,180);}
    void previousWord(){if(history.isEmpty()){Toast.makeText(this,"已经是第一个单词",Toast.LENGTH_SHORT).show();return;}Word previous=db.wordById(history.remove(history.size()-1));if(previous!=null){current=previous;renderCard();}}
    Button footerButton(String label,int c){Button b=button(label);color(b,c);return b;}
    void reveal(View hint){if(revealed)return;revealed=true;root.setContentDescription(null);hint.setVisibility(View.GONE);content.setGravity(Gravity.CENTER_HORIZONTAL);TextView ipa=text(s(current.ipa)+"  "+s(current.pos),18,muted);ipa.setGravity(Gravity.CENTER);content.addView(ipa);gap(5);LinearLayout meaning=card();meaning.setGravity(Gravity.CENTER);meaning.setBackground(bg(Color.rgb(252,247,235),20));TextView zh=text(current.zh,27,ink);zh.setTypeface(null,Typeface.BOLD);zh.setGravity(Gravity.CENTER);meaning.addView(zh,new LinearLayout.LayoutParams(-1,-2));if(!s(current.en).trim().isEmpty()){TextView en=text(current.en,15,muted);en.setGravity(Gravity.CENTER);meaning.addView(en);}addCard(meaning);if(!s(current.exampleEn).trim().isEmpty()){LinearLayout brief=card();brief.setBackground(bg(Color.rgb(242,246,244),18));brief.addView(text(current.exampleEn,17,ink));addCard(brief);}actions.setVisibility(View.VISIBLE);
        LinearLayout tools=new LinearLayout(this);Button previous=footerButton("← 上一词",Color.rgb(70,92,87));previous.setOnClickListener(v->previousWord());Button sound=footerButton("🔊 再听",teal);sound.setOnClickListener(v->playAudio());Button edit=footerButton("✎ 编辑",Color.rgb(62,92,132));edit.setOnClickListener(v->editWord());tools.addView(previous,new LinearLayout.LayoutParams(0,dp(55),1));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,dp(55),1);tp.setMargins(dp(6),0,dp(6),0);tools.addView(sound,tp);tools.addView(edit,new LinearLayout.LayoutParams(0,dp(55),1));actions.addView(tools);
        Button favorite=footerButton(db.isFavorite(current.id)?"★ 已收藏（点击取消）":"☆ 收藏这个单词",Color.rgb(190,130,32));favorite.setOnClickListener(v->{boolean yes=db.toggleFavorite(current.id);favorite.setText(yes?"★ 已收藏（点击取消）":"☆ 收藏这个单词");Toast.makeText(this,yes?"已加入全局收藏":"已取消收藏",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(55));fp.setMargins(0,dp(7),0,dp(7));actions.addView(favorite,fp);
        LinearLayout decisions=new LinearLayout(this);Button mark=footerButton("✓ 标记已掌握",teal);applyMasterButton(mark,db.isMastered(current.id));mark.setOnClickListener(v->{boolean yes=!db.isMastered(current.id);db.setMastered(current.id,yes);current.mastered=yes;if(yes){Toast.makeText(this,"已掌握；如需撤销可点上一词",Toast.LENGTH_SHORT).show();showCard();}else{applyMasterButton(mark,false);Toast.makeText(this,"已撤销掌握",Toast.LENGTH_SHORT).show();}});Button next=footerButton("暂不掌握 →",Color.rgb(80,98,93));next.setOnClickListener(v->advanceWithoutMastery());decisions.addView(mark,new LinearLayout.LayoutParams(0,dp(61),1));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(0,dp(61),1);np.setMargins(dp(8),0,0,0);decisions.addView(next,np);actions.addView(decisions);}
    void advanceWithoutMastery(){if(current==null)return;long old=current.id;history.add(old);db.skip(old);Word following=db.nextExcluding(old);if(following==null)following=db.next();if(following==null){showHome();Toast.makeText(this,"词库已经全部掌握",Toast.LENGTH_LONG).show();return;}current=following;renderCard();}
    void applyMasterButton(Button b,boolean yes){b.setText(yes?"↶ 撤销已掌握":"✓ 标记已掌握");color(b,yes?red:teal);}
    String s(String x){return x==null?"":x;}

    EditText field(String label,String value,LinearLayout box,boolean multiline){TextView l=text(label,14,tealDark);l.setTypeface(null,Typeface.BOLD);box.addView(l);EditText e=new EditText(this);e.setText(s(value));e.setTextSize(16);e.setTextColor(ink);e.setBackground(bg(Color.rgb(242,246,244),12));e.setPadding(dp(12),dp(10),dp(12),dp(10));e.setSingleLine(!multiline);if(multiline){e.setMinLines(2);e.setGravity(Gravity.TOP);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(9));box.addView(e,p);return e;}
    void editWord(){ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(8),dp(18),dp(8));EditText term=field("单词",current.term,box,false),ipa=field("音标",current.ipa,box,false),pos=field("词性",current.pos,box,false),zh=field("中文释义",current.zh,box,true),en=field("英文释义",current.en,box,true),brief=field("精简说明（example_en / usage_brief_zh）",current.exampleEn,box,true);sc.addView(box);new AlertDialog.Builder(this).setTitle("编辑当前词条").setView(sc).setPositiveButton("保存",(d,w)->{current.term=term.getText().toString().trim();current.ipa=ipa.getText().toString().trim();current.pos=pos.getText().toString().trim();current.zh=zh.getText().toString().trim();current.en=en.getText().toString().trim();current.exampleEn=brief.getText().toString().trim();if(current.term.isEmpty()){Toast.makeText(this,"单词不能为空",Toast.LENGTH_SHORT).show();return;}db.updateWord(current);renderCard();Toast.makeText(this,"已保存；导出 Excel 时会写入修改",Toast.LENGTH_LONG).show();}).setNegativeButton("取消",null).show();}

    void showCheckIn(){revealed=true;base("今日打卡");savedCheckInUri=null;db.ensureRound();int learned=db.studiedToday(),mt=db.masteredToday(),mastered=db.mastered(),total=db.total(),round=db.currentRound(),roundDone=db.roundDone(),roundTotal=db.roundTotal();Word featured=db.randomUnmastered();checkInPoster=new FrameLayout(this);checkInPoster.setBackground(bg(tealDark,24));SharedPreferences checkPrefs=getSharedPreferences("checkin",0);String uri=checkPrefs.getString("background","");if(!uri.isEmpty()){try{CheckInImageView image=new CheckInImageView(this);image.setImageURI(Uri.parse(uri));image.setAlpha(.68f);image.setTransform(checkPrefs.getFloat("scale",1f),checkPrefs.getFloat("x",0f),checkPrefs.getFloat("y",0f));image.setChangeListener((scale,x,y)->checkPrefs.edit().putFloat("scale",scale).putFloat("x",x).putFloat("y",y).apply());checkInPoster.addView(image,new FrameLayout.LayoutParams(-1,-1));}catch(Exception ignored){}}
        LinearLayout overlay=new LinearLayout(this);overlay.setOrientation(LinearLayout.VERTICAL);overlay.setGravity(Gravity.CENTER);overlay.setPadding(dp(22),dp(20),dp(22),dp(20));overlay.setBackgroundColor(Color.argb(112,0,35,31));TextView title=text("今日学习打卡",27,Color.WHITE);title.setTypeface(null,Typeface.BOLD);title.setGravity(Gravity.CENTER);overlay.addView(title);TextView date=text(new SimpleDateFormat("yyyy年M月d日 EEEE",Locale.getDefault()).format(new Date()),16,Color.rgb(224,241,235));date.setGravity(Gravity.CENTER);overlay.addView(date);TextView nums=text("今日学习 "+learned+" 词   ·   新掌握 "+mt+" 词",21,Color.WHITE);nums.setTypeface(null,Typeface.BOLD);nums.setGravity(Gravity.CENTER);overlay.addView(nums);overlay.addView(text("第 "+round+" 轮  "+roundDone+" / "+roundTotal,16,Color.WHITE));overlay.addView(text("词书总掌握  "+mastered+" / "+total+String.format(Locale.getDefault(),"  ·  %.1f%%",total==0?0:mastered*100.0/total),16,Color.WHITE));ProgressBar p=progress(total,mastered,Color.WHITE);overlay.addView(p,new LinearLayout.LayoutParams(-1,dp(11)));if(featured!=null){TextView featuredTerm=text(featured.term,31,Color.WHITE);featuredTerm.setGravity(Gravity.CENTER);featuredTerm.setTypeface(Typeface.create("serif",Typeface.BOLD));overlay.addView(featuredTerm);TextView featuredInfo=text(s(featured.ipa)+"   "+s(featured.pos)+"\n"+s(featured.zh),16,Color.rgb(240,247,244));featuredInfo.setGravity(Gravity.CENTER);featuredInfo.setTypeface(Typeface.create("sans-serif-light",Typeface.NORMAL));overlay.addView(featuredInfo);if(!s(featured.exampleEn).trim().isEmpty()){TextView brief=text(featured.exampleEn,16,Color.WHITE);brief.setGravity(Gravity.CENTER);brief.setTypeface(Typeface.create("sans-serif-light",Typeface.NORMAL));overlay.addView(brief);}}checkInPoster.addView(overlay,new FrameLayout.LayoutParams(-1,-1));content.addView(checkInPoster,new LinearLayout.LayoutParams(-1,dp(410)));
        Button done=button(db.checkedToday()?"✓ 更新并保存打卡图片":"完成打卡并保存图片");done.setOnClickListener(v->{db.checkIn();done.setText("✓ 今日已打卡");color(done,tealDark);saveCheckIn(null);});addCard(done);Button share=button("分享到微信 / 其他应用");color(share,Color.rgb(44,146,87));share.setOnClickListener(v->{if(savedCheckInUri==null)saveCheckIn(this::shareCheckIn);else shareCheckIn();});addCard(share);Button image=button("选择本地图片作为打卡底图");color(image,Color.rgb(62,92,132));image.setOnClickListener(v->chooseCheckInImage());addCard(image);Button back=button("返回首页");color(back,Color.rgb(80,98,93));back.setOnClickListener(v->showHome());addCard(back);content.addView(text("在打卡卡片上单指拖动底图、双指缩放；完成后 PNG 自动保存到相册。",14,muted));}
    void chooseCheckInImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,44);}

    void saveCheckIn(Runnable after){if(checkInPoster==null||checkInPoster.getWidth()==0){Toast.makeText(this,"打卡图片尚未准备好",Toast.LENGTH_SHORT).show();return;}if(Build.VERSION.SDK_INT<29&&checkSelfPermission(android.Manifest.permission.WRITE_EXTERNAL_STORAGE)!=android.content.pm.PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.WRITE_EXTERNAL_STORAGE},51);Toast.makeText(this,"请授权保存图片后再次点击",Toast.LENGTH_LONG).show();return;}try{Bitmap bitmap=Bitmap.createBitmap(checkInPoster.getWidth(),checkInPoster.getHeight(),Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(bitmap);checkInPoster.draw(canvas);String name="雅思单词库打卡-"+new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date())+".png";if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,"image/png");v.put(MediaStore.Images.Media.RELATIVE_PATH,android.os.Environment.DIRECTORY_PICTURES+"/雅思单词库");savedCheckInUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);try(OutputStream o=getContentResolver().openOutputStream(savedCheckInUri)){bitmap.compress(Bitmap.CompressFormat.PNG,100,o);}}else{String url=MediaStore.Images.Media.insertImage(getContentResolver(),bitmap,name,"雅思单词库学习打卡");savedCheckInUri=Uri.parse(url);}bitmap.recycle();Toast.makeText(this,"打卡图片已保存到相册",Toast.LENGTH_LONG).show();if(after!=null)after.run();}catch(Exception e){Toast.makeText(this,"保存打卡图片失败："+e.getMessage(),Toast.LENGTH_LONG).show();}}
    void shareCheckIn(){if(savedCheckInUri==null){Toast.makeText(this,"请先完成并保存打卡",Toast.LENGTH_SHORT).show();return;}Intent i=new Intent(Intent.ACTION_SEND);i.setType("image/png");i.putExtra(Intent.EXTRA_STREAM,savedCheckInUri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);Intent wechat=new Intent(i);wechat.setPackage("com.tencent.mm");if(wechat.resolveActivity(getPackageManager())!=null)startActivity(wechat);else startActivity(Intent.createChooser(i,"分享打卡图片"));}

    void playAudio(){try{if(player!=null)player.release();String path=s(current.audio).replace("audio/uk/","audio/");android.content.res.AssetFileDescriptor afd=getAssets().openFd(path);player=new MediaPlayer();player.setDataSource(afd.getFileDescriptor(),afd.getStartOffset(),afd.getLength());afd.close();player.prepare();player.start();}catch(Exception e){fetchAudio();}}
    void fetchAudio(){File cached=new File(getCacheDir(),"audio_"+current.id+".mp3");if(cached.exists()){playFile(cached);return;}String term=current.term;new Thread(()->{try{URL api=new URL("https://api.dictionaryapi.dev/api/v2/entries/en/"+URLEncoder.encode(term,"UTF-8"));HttpURLConnection c=(HttpURLConnection)api.openConnection();c.setConnectTimeout(7000);c.setReadTimeout(7000);JSONArray a=new JSONArray(readAll(c.getInputStream()));JSONArray ps=a.getJSONObject(0).getJSONArray("phonetics");String audio="";for(int i=0;i<ps.length();i++){audio=ps.getJSONObject(i).optString("audio","");if(!audio.isEmpty())break;}if(audio.startsWith("//"))audio="https:"+audio;if(audio.isEmpty())throw new IOException("no audio");try(InputStream in=new URL(audio).openStream();OutputStream out=new FileOutputStream(cached)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);}runOnUiThread(()->playFile(cached));}catch(Exception ex){runOnUiThread(()->Toast.makeText(this,"未找到在线发音",Toast.LENGTH_SHORT).show());}}).start();}
    String readAll(InputStream in)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))>0)o.write(b,0,n);return o.toString("UTF-8");}
    void playFile(File f){try{if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.prepare();player.start();}catch(Exception ignored){}}

    void exportExcel(boolean favorites){if(favorites&&db.favoriteCount()==0){Toast.makeText(this,"还没有收藏单词",Toast.LENGTH_SHORT).show();return;}try{pendingExport=XlsxExporter.write(favorites?db.exportFavorites():db.exportRows());Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");i.putExtra(Intent.EXTRA_TITLE,favorites?"收藏单词-全局.xlsx":"学习状态-"+db.name("books",db.bookId)+".xlsx");startActivityForResult(i,42);}catch(Exception e){Toast.makeText(this,"生成 Excel 失败",Toast.LENGTH_SHORT).show();}}
    @Override protected void onActivityResult(int r,int code,Intent data){super.onActivityResult(r,code,data);if(code!=RESULT_OK||data==null)return;if(r==43){importExcel(data.getData());return;}if(r==44){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}getSharedPreferences("checkin",0).edit().putString("background",u.toString()).putFloat("scale",1f).putFloat("x",0f).putFloat("y",0f).apply();showCheckIn();return;}if(r==42&&pendingExport!=null){try(OutputStream o=getContentResolver().openOutputStream(data.getData())){o.write(pendingExport);Toast.makeText(this,"导出完成，可再次导入恢复词库与状态",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"导出失败",Toast.LENGTH_SHORT).show();}}}
    void error(Exception e){base("初始化失败");content.addView(text(e.getMessage(),16,Color.RED));}
    @Override public boolean dispatchTouchEvent(android.view.MotionEvent event){if(!revealed&&revealHint!=null){if(event.getAction()==android.view.MotionEvent.ACTION_UP)reveal(revealHint);return true;}return super.dispatchTouchEvent(event);}
    @Override public void onBackPressed(){showHome();}
    @Override protected void onDestroy(){if(player!=null)player.release();db.close();super.onDestroy();}
}
