package com.personal.offlinewords;
import android.content.*;import android.database.Cursor;import android.database.sqlite.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
final class WordDb extends SQLiteOpenHelper {
 private final Context ctx; long bookId,profileId; WordDb(Context c){super(c,"words.db",null,3);ctx=c;bookId=c.getSharedPreferences("selection",0).getLong("book",1);profileId=c.getSharedPreferences("selection",0).getLong("profile",1);}
 public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE books(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE profiles(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE words(id INTEGER PRIMARY KEY AUTOINCREMENT,book_id INTEGER,sort_order INTEGER,term TEXT,ipa TEXT,pos TEXT,zh TEXT,en TEXT,example_en TEXT,example_zh TEXT,audio TEXT)");d.execSQL("CREATE TABLE states(profile_id INTEGER,word_id INTEGER,mastered INTEGER DEFAULT 0,last_seen INTEGER DEFAULT 0,favorite INTEGER DEFAULT 0,PRIMARY KEY(profile_id,word_id))");d.execSQL("INSERT INTO books(name) VALUES('雅思 9400')");d.execSQL("INSERT INTO profiles(name) VALUES('默认进度')");}
 public void onUpgrade(SQLiteDatabase d,int a,int b){if(a<3)d.execSQL("ALTER TABLE states ADD COLUMN favorite INTEGER DEFAULT 0");}
 void seedIfNeeded(Context c)throws Exception{final int dataVersion=2026071402;android.content.SharedPreferences prefs=c.getSharedPreferences("data_version",0);if(prefs.getInt("default_words",0)==dataVersion)return;SQLiteDatabase d=getWritableDatabase();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;try(InputStream in=c.getAssets().open("words.json")){while((n=in.read(b))>0)o.write(b,0,n);}JSONArray a=new JSONArray(o.toString(StandardCharsets.UTF_8.name()));d.beginTransaction();try{SQLiteStatement update=d.compileStatement("UPDATE words SET term=?,ipa=?,pos=?,zh=?,en=?,example_en=?,example_zh=?,audio=? WHERE book_id=1 AND sort_order=?");SQLiteStatement insert=d.compileStatement("INSERT INTO words(book_id,sort_order,term,ipa,pos,zh,en,example_en,example_zh,audio) VALUES(1,?,?,?,?,?,?,?,?,?)");for(int i=0;i<a.length();i++){JSONArray r=a.getJSONArray(i);update.clearBindings();for(int j=1;j<9;j++)update.bindString(j,r.optString(j,""));update.bindLong(9,r.getLong(0));if(update.executeUpdateDelete()==0){insert.clearBindings();insert.bindLong(1,r.getLong(0));for(int j=1;j<9;j++)insert.bindString(j+1,r.optString(j,""));insert.executeInsert();}}d.setTransactionSuccessful();}finally{d.endTransaction();}prefs.edit().putInt("default_words",dataVersion).apply();}
 Word next(){Cursor c=getReadableDatabase().rawQuery("SELECT w.id,w.term,w.ipa,w.pos,w.zh,w.en,w.example_en,w.example_zh,w.audio FROM words w LEFT JOIN states s ON s.word_id=w.id AND s.profile_id=? WHERE w.book_id=? AND COALESCE(s.mastered,0)=0 ORDER BY COALESCE(s.last_seen,0),w.sort_order LIMIT 1",new String[]{""+profileId,""+bookId});try{if(!c.moveToFirst())return null;Word w=new Word();w.id=c.getLong(0);w.term=c.getString(1);w.ipa=c.getString(2);w.pos=c.getString(3);w.zh=c.getString(4);w.en=c.getString(5);w.exampleEn=c.getString(6);w.exampleZh=c.getString(7);w.audio=c.getString(8);return w;}finally{c.close();}}
 Word wordById(long id){Cursor c=getReadableDatabase().rawQuery("SELECT id,term,ipa,pos,zh,en,example_en,example_zh,audio FROM words WHERE id=?",new String[]{""+id});try{if(!c.moveToFirst())return null;Word w=new Word();w.id=c.getLong(0);w.term=c.getString(1);w.ipa=c.getString(2);w.pos=c.getString(3);w.zh=c.getString(4);w.en=c.getString(5);w.exampleEn=c.getString(6);w.exampleZh=c.getString(7);w.audio=c.getString(8);return w;}finally{c.close();}}
 void markMastered(long id){getWritableDatabase().execSQL("INSERT INTO states(profile_id,word_id,mastered,last_seen) VALUES(?,?,1,?) ON CONFLICT(profile_id,word_id) DO UPDATE SET mastered=1,last_seen=excluded.last_seen",new Object[]{profileId,id,System.currentTimeMillis()});}void skip(long id){getWritableDatabase().execSQL("INSERT INTO states(profile_id,word_id,mastered,last_seen) VALUES(?,?,0,?) ON CONFLICT(profile_id,word_id) DO UPDATE SET last_seen=excluded.last_seen",new Object[]{profileId,id,System.currentTimeMillis()});}
 boolean isFavorite(long id){return scalar("SELECT count(*) FROM states WHERE profile_id=? AND word_id=? AND favorite=1",profileId,id)>0;}
 boolean toggleFavorite(long id){boolean next=!isFavorite(id);getWritableDatabase().execSQL("INSERT INTO states(profile_id,word_id,favorite) VALUES(?,?,?) ON CONFLICT(profile_id,word_id) DO UPDATE SET favorite=excluded.favorite",new Object[]{profileId,id,next?1:0});return next;}
 int favoriteCount(){return scalar("SELECT count(*) FROM states WHERE profile_id=? AND favorite=1",profileId);}
 int total(){return scalar("SELECT count(*) FROM words WHERE book_id=?",bookId);}int mastered(){return scalar("SELECT count(*) FROM states s JOIN words w ON w.id=s.word_id WHERE profile_id=? AND book_id=? AND mastered=1",profileId,bookId);}int scalar(String q,long...v){String[] a=new String[v.length];for(int i=0;i<v.length;i++)a[i]=""+v[i];Cursor c=getReadableDatabase().rawQuery(q,a);try{c.moveToFirst();return c.getInt(0);}finally{c.close();}}
 Cursor exportRows(){return getReadableDatabase().rawQuery("SELECT w.sort_order,w.term,w.ipa,w.pos,w.zh,CASE WHEN COALESCE(s.mastered,0)=1 THEN '已掌握' ELSE '学习中' END,COALESCE(s.last_seen,0) FROM words w LEFT JOIN states s ON s.word_id=w.id AND s.profile_id=? WHERE w.book_id=? ORDER BY w.sort_order",new String[]{""+profileId,""+bookId});}
 Cursor exportFavorites(){return getReadableDatabase().rawQuery("SELECT w.sort_order,w.term,w.ipa,w.pos,w.zh,CASE WHEN s.mastered=1 THEN '已掌握' ELSE '学习中' END,s.last_seen FROM words w JOIN states s ON s.word_id=w.id AND s.profile_id=? WHERE s.favorite=1 ORDER BY w.book_id,w.sort_order",new String[]{""+profileId});}
 long importBook(String name,List<String[]> rows){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{ContentValues v=new ContentValues();v.put("name",name);long id=d.insertOrThrow("books",null,v);SQLiteStatement s=d.compileStatement("INSERT INTO words(book_id,sort_order,term,ipa,pos,zh,en,example_en,example_zh,audio) VALUES(?,?,?,?,?,?,?,?,?,?)");for(int i=0;i<rows.size();i++){String[] r=rows.get(i);s.clearBindings();s.bindLong(1,id);long order=i+1;try{order=Long.parseLong(r[0].replace(".0",""));}catch(Exception ignored){}s.bindLong(2,order);for(int j=1;j<9;j++)s.bindString(j+2,r[j]==null?"":r[j]);s.executeInsert();}d.setTransactionSuccessful();return id;}finally{d.endTransaction();}}
 boolean deleteBook(long id){if(id==1)return false;SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{d.execSQL("DELETE FROM states WHERE word_id IN(SELECT id FROM words WHERE book_id=?)",new Object[]{id});d.delete("words","book_id=?",new String[]{""+id});d.delete("books","id=?",new String[]{""+id});d.setTransactionSuccessful();select(1,profileId);return true;}finally{d.endTransaction();}}
 int count(String legacy){return legacy.contains("-1")?mastered():total();}
 Cursor books(){return getReadableDatabase().rawQuery("SELECT id,name FROM books ORDER BY id",null);}Cursor profiles(){return getReadableDatabase().rawQuery("SELECT id,name FROM profiles ORDER BY id",null);}long addProfile(String n){ContentValues v=new ContentValues();v.put("name",n);return getWritableDatabase().insert("profiles",null,v);}void select(long b,long p){bookId=b;profileId=p;ctx.getSharedPreferences("selection",0).edit().putLong("book",b).putLong("profile",p).apply();}String name(String t,long id){Cursor c=getReadableDatabase().rawQuery("SELECT name FROM "+t+" WHERE id=?",new String[]{""+id});try{return c.moveToFirst()?c.getString(0):"";}finally{c.close();}}
}
